version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq-con
    hostname: rabbitmq-host
    ports:
      - 8088:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=best
      - RABBITMQ_DEFAULT_PASS=best
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: